export const Update_Order_Front = 'Update_Order_Front';
export const Add_New_Orders = 'New_Replace_Orders';
export const Update_BookOrderForm_Values = 'Update_BookOrderForm_Values';
export const Order_Type_ask = 'ask';
export const Order_Type_bid = 'bid';
export const Total_Orders_TillNow = "Total_Order"
export const Clear_Prev_TotalOrders = "Clear_Prev_TotalOrders"
export const Clear_BookOrderForm_Values = "clear_BookOrderForm_Values"
export const Fetch_Stock_Symbols = "Fetch_Stock_Symbols";
export const Load_Stock_Symbols = "Load_Stock_Symbols";
export const Set_User_Details = "Set_User_Details";
export const Add_To_Ask_TOrders="Add_To_Ask_TOrders";
export const Add_To_Bid_TOrders="Add_To_Bid_TOrders";
export const Set_LoginForm_ValidityState="Set_LoginForm_ValidityState";
export const Clear_BidAsk_List_Orders="Clear_BidAsk_List_Orders"
export const Load_Booked_Orders="Load_Booked_Orders";
export const Load_Executed_Orders="Load_Executed_Orders";
export const Fetch_Booked_Orders="Fetch_Booked_Orders";
export const Fetch_Executed_Orders="Fetch_Executed_Orders";